// Generated by gencpp from file nao_interaction_msgs/AudioMasterVolumeRequest.msg
// DO NOT EDIT!


#ifndef NAO_INTERACTION_MSGS_MESSAGE_AUDIOMASTERVOLUMEREQUEST_H
#define NAO_INTERACTION_MSGS_MESSAGE_AUDIOMASTERVOLUMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>

namespace nao_interaction_msgs
{
template <class ContainerAllocator>
struct AudioMasterVolumeRequest_
{
  typedef AudioMasterVolumeRequest_<ContainerAllocator> Type;

  AudioMasterVolumeRequest_()
    : master_volume()  {
    }
  AudioMasterVolumeRequest_(const ContainerAllocator& _alloc)
    : master_volume(_alloc)  {
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _master_volume_type;
  _master_volume_type master_volume;




  typedef boost::shared_ptr< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AudioMasterVolumeRequest_

typedef ::nao_interaction_msgs::AudioMasterVolumeRequest_<std::allocator<void> > AudioMasterVolumeRequest;

typedef boost::shared_ptr< ::nao_interaction_msgs::AudioMasterVolumeRequest > AudioMasterVolumeRequestPtr;
typedef boost::shared_ptr< ::nao_interaction_msgs::AudioMasterVolumeRequest const> AudioMasterVolumeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace nao_interaction_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'nao_interaction_msgs': ['/home/gary/catkin_ws/src/nao_interaction_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a2d45c5fcf9fd89299667da81b32d64";
  }

  static const char* value(const ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a2d45c5fcf9fd89ULL;
  static const uint64_t static_value2 = 0x299667da81b32d64ULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_interaction_msgs/AudioMasterVolumeRequest";
  }

  static const char* value(const ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
std_msgs/Int32 master_volume\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
";
  }

  static const char* value(const ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.master_volume);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AudioMasterVolumeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_interaction_msgs::AudioMasterVolumeRequest_<ContainerAllocator>& v)
  {
    s << indent << "master_volume: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.master_volume);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_INTERACTION_MSGS_MESSAGE_AUDIOMASTERVOLUMEREQUEST_H
